name: "Generate sBOM"
on: push

jobs:
  build-and-generate-sbom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate sBOM
        id: generate-sbom
        uses: ajmalab/actions-sbom-generator/v1
       



