name: "Generate sBOM"
on: push

jobs:
  build-and-generate-sbom:
    runs-on: ubuntu-latest
    steps:
      - name: Generate sBOM
        id: generate-sbom
        shell: bash
        uses: ajmalab/actions-sbom-generator@v4




